version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-apache
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      # SSL
      - ./apache/ssl/example.com-key.pem:/etc/apache2/ssl/example.com-key.pem
      - ./apache/ssl/example.com.pem:/etc/apache2/ssl/example.com.pem
      # Uncomment the code if you want to see logs.
      # - ./apache/log:/var/log/apache2/
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db
    networks:
      - app-db
      - app-phpmyadmin

  db:
    image: mariadb
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-db
      - db-phpmyadmin
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=laravel-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - ./phpmyadmin/sessions:/sessions
    ports:
      - 8000:80
    links:
      - db
    depends_on:
      - db
    networks:
      - app-phpmyadmin
      - db-phpmyadmin

networks:
  app-db:
    driver: bridge
  app-phpmyadmin:
    driver: bridge
  db-phpmyadmin:
    driver: bridge
